releases:
- (( merge ))
- name: logsearch-for-cloudfoundry-operators
  version: latest

jobs:
- name: parser
  templates:
  - (( merge ))
  - {name: parsing-rules, release: logsearch-for-cloudfoundry-operators}
  properties:
    logstash_parser:
      filters:
      - logsearch-for-cf: /var/vcap/packages/parsing-rules/logstash-filters-default.conf


- name: haproxy
  instances: 1
  templates:
  - (( merge ))
  - {name: route_registrar, release: logsearch-for-cloudfoundry-operators}
  properties:
    route_registrar:
      routes:
      - name: logsearch
        port: 80
        registration_interval: 20s
      - name: logsearch_monitor
        port: 8080
        registration_interval: 20s

properties:
  haproxy:
    kibana:
      auth:
        username: username
        password: password
    cluster_monitor:
      auth:
        username: username
        password: password
  cf:
    system_domain: cf_system_domain
    nats:
      host: nats-ip
      port: 4222
      username: nats
      password: nats-password
