releases:
- (( merge ))
- name: logsearch-for-cloudfoundry-operators
  version: latest

jobs:
- name: parser
  templates:
  - (( merge ))
  - {name: parsing-rules-for-cf-ops, release: logsearch-for-cloudfoundry-operators}
  properties:
    logstash_parser:
      filters:
      - logsearch-for-cf: /var/vcap/packages/parsing-rules-for-cf-ops/logstash-filters-default.conf


- name: firehose-to-syslog
  instances: 0
  resource_pool: haproxy #because it's small by default
  networks:
  - name: default
  templates:
  - { release: logsearch-for-cloudfoundry-operators, name: ingestor_cloudfoundry-firehose }
  properties:
    cloudfoundry:
      api_endpoint: cf_api_url
      system_domain: cf_system_domain
      skip_ssl_validation: false
      firehose_port: 4443
      firehose_user: doppler
      firehose_password: firehose-password
      firehose_events: "HttpStart,HttpStop,HttpStartStop,LogMessage,ValueMetric,CounterEvent,Error,ContainerMetric,HttpStart"
    syslog:
      host: (( grab jobs.ls-router.networks.default.static_ips.[0] ))
      port: 514

